import { createTheme, MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { createRootRouteWithContext, Outlet } from "@tanstack/react-router";
import { RootRouteContext } from "@/types/RootRouteContext";

/**
 * Our primary brand color.
 * The scale is generated by uicolors.app with #1563fe as the base
 */
const AVANDAR_BLUE_SHADES = [
  "#edf6ff",
  "#d8ebff",
  "#b9dcff",
  "#89c7ff",
  "#51a7ff",
  "#2983ff",
  "#1563fe", // primary color
  "#0b4aea",
  "#103dbd",
  "#143894",
  "#11245a",
] as const;

const PRIMARY_SHADE = 6;

const QUERY_CLIENT = new QueryClient();

const THEME = createTheme({
  colors: {
    "avandar-blue": AVANDAR_BLUE_SHADES,
  },
  // fontFamily: "Figtree, sans-serif",
  fontFamily: "Figtree, Comic Sans MS",
  primaryShade: PRIMARY_SHADE,
  primaryColor: "avandar-blue",
});

/**
 * This is the root route of the app. It only renders the <App> component.
 */
export const Route = createRootRouteWithContext<RootRouteContext>()({
  component: RootComponent,
});

function RootComponent() {
  return (
    <QueryClientProvider client={QUERY_CLIENT}>
      <MantineProvider theme={THEME}>
        <Notifications />
        <Outlet />
      </MantineProvider>
    </QueryClientProvider>
  );
}
