-- Generated from supabase/migrations/20260515160000_resource_share_rls_and_drop_user_roles.sql by
-- apps/desktop/scripts/gen-sqlite-migrations.ts. Do not edit by hand
-- unless the matching `needs hand-edit` warning calls for it.
-- Schema-shape statements emitted: 0
-- Statements dropped (RLS/funcs/triggers/data/etc.): 21
-- Statements needing hand-edit (ADD CONSTRAINT, ALTER COLUMN): 0
-- No schema-shape changes: every statement was RLS / GRANT / function / trigger / type / data backfill, none of which has a SQLite equivalent.
