/**
 * The lifecycle status of a background job.
 *
 * - `in_progress`   — the job is currently executing.
 * - `completed`     — the job finished successfully.
 * - `failed`        — the job finished with an error.
 * - `canceled`      — the job was canceled by the user or the system.
 * - `indeterminate` — the job's outcome is unknown. The most common cause
 *                     is that the tab was closed or refreshed while the
 *                     job was in flight and we lost track of it.
 */
export type BackgroundJobStatus =
  | "in_progress"
  | "completed"
  | "failed"
  | "canceled"
  | "indeterminate";

/**
 * A user-facing toast message that should be shown when a job reaches a
 * given terminal state. The `BackgroundJobStore` invokes the configured
 * notifier with this payload on the matching transition.
 */
export type BackgroundJobToast = {
  title: string;
  message?: string;
};

/**
 * The full set of fields that describe a background job. This is the
 * shape stored in dexie (for persistent jobs) and held in memory by the
 * `BackgroundJobStore`.
 *
 * Jobs themselves decide whether they should persist across refreshes
 * via `persistAcrossRefresh`. The store does not know or care what kind
 * of work a job is doing — it just tracks metadata and status.
 */
export type BackgroundJob = {
  /** Stable unique id. Generated by the store on register. */
  id: string;

  /**
   * Free-form type tag used to group similar jobs in the UI. Examples:
   * `"dataset-parse"`, `"dataset-upload"`, `"voice-model-download"`.
   */
  type: string;

  /** Short user-facing label, e.g. "Importing 'sales.csv'". */
  label: string;

  /** Optional longer description shown in the jobs list. */
  description?: string;

  status: BackgroundJobStatus;

  /**
   * Optional 0–100 progress percentage. Undefined for jobs that do not
   * report progress.
   */
  progress?: number;

  /**
   * When true, the job is mirrored to dexie so it survives a tab refresh.
   * On boot, persistent jobs that were `in_progress` are demoted to
   * `indeterminate` because we have no way to know whether the work
   * actually finished.
   */
  persistAcrossRefresh: boolean;

  /** Wall-clock ms when the job was registered. */
  createdAt: number;

  /** Wall-clock ms when the job entered a terminal status. */
  finishedAt?: number;

  /** Failure reason when `status === "failed"`. */
  errorMessage?: string;

  /**
   * Optional metadata blob. Free-form. The store treats this opaquely.
   * Useful for callers that need to reconstruct context after a refresh
   * (e.g. the dataset id a job is acting on).
   */
  metadata?: Record<string, unknown>;

  /** Toast to show on `completed`. */
  successToast?: BackgroundJobToast;

  /** Toast to show on `failed`. */
  failureToast?: BackgroundJobToast;

  /** Toast to show on `canceled`. */
  cancelToast?: BackgroundJobToast;
};

/**
 * Fields a caller provides when registering a new job. All lifecycle
 * fields (`id`, `status`, `createdAt`) are filled in by the store.
 */
export type RegisterBackgroundJobInput = {
  type: string;
  label: string;
  description?: string;
  progress?: number;
  persistAcrossRefresh?: boolean;
  metadata?: Record<string, unknown>;
  successToast?: BackgroundJobToast;
  failureToast?: BackgroundJobToast;
  cancelToast?: BackgroundJobToast;
  /**
   * Optional stable id. If provided and a job with the same id already
   * exists, the existing job is returned instead of creating a new one.
   * Useful for idempotent registration keyed by, e.g., a dataset id.
   */
  id?: string;
};
