import type { Model } from "@models/Model/Model.ts";
import type { UUID } from "@utils/types/common.types.ts";
import type {
  ChatClarifyRequest,
  ChatGeneratedDashboardBlock,
} from "$/types/chat.types.ts";

type ModelType = "ChatResponse";

/** SQL generated by the assistant for the data explorer canvas. */
export type ChatGeneratedSql = {
  prompt: string;
  sql: string;
};

export type ChatResponseId = UUID<ModelType>;

export type ChatResponseRead = Model.Base<
  ModelType,
  {
    assistantText: string;
    generatedSql?: ChatGeneratedSql;
    /**
     * Present when the model called the `clarify` tool. The client renders
     * the clarification UI inline in the thread; on answer it issues a new
     * turn with a `[Clarification answer: ...]` user message.
     */
    clarification?: ChatClarifyRequest;
    /**
     * Present when the model called the `addDashboardBlock` tool while the
     * user was editing a dashboard. The frontend appends the block to the
     * Puck data via `DashboardEditorStateManager.queuePendingBlock`.
     */
    dashboardBlock?: ChatGeneratedDashboardBlock;
  }
>;

export type ChatResponseModel = {
  Read: ChatResponseRead;
};
