import type { Model } from "@avandar/models";
import type { UUID } from "@avandar/utils";
import type {
  ChatClarifyRequest,
  ChatCreatedCaseType,
  ChatGeneratedDashboardBlock,
  ChatProposedCaseType,
} from "$/types/chat.types.ts";

type ModelType = "ChatResponse";

/** SQL generated by the assistant for the data explorer canvas. */
export type ChatGeneratedSql = {
  prompt: string;
  sql: string;
};

export type ChatResponseId = UUID<ModelType>;

export type ChatResponseRead = Model.Base<
  ModelType,
  {
    assistantText: string;
    generatedSql?: ChatGeneratedSql;
    /**
     * Present when the model called the `clarify` tool. The client renders
     * the clarification UI inline in the thread; on answer it issues a new
     * turn with a `[Clarification answer: ...]` user message.
     */
    clarification?: ChatClarifyRequest;
    /**
     * Present when the model called the `addDashboardBlock` tool while the
     * user was editing a dashboard. The frontend appends the block to the
     * Puck data via `DashboardEditorStateManager.queuePendingBlock`.
     */
    dashboardBlock?: ChatGeneratedDashboardBlock;
    /**
     * Present when the model called `createCaseTypes` in Case Manager.
     * The client inserts the concepts with the same path as the creator form.
     */
    createdCaseTypes?: readonly ChatCreatedCaseType[];
    /**
     * Present when the model called `proposeCaseType` in Case Manager. The
     * client renders it as an editable draft card and only persists the concept
     * once the user confirms, so nothing reaches the database from this field.
     */
    proposedCaseType?: ChatProposedCaseType;
  }
>;

export type ChatResponseModel = {
  Read: ChatResponseRead;
};
