import { createTheme } from "@mantine/core";

const AVANDAR_BLUE_SHADES = [
  "#edf6ff",
  "#d8ebff",
  "#b9dcff",
  "#89c7ff",
  "#51a7ff",
  "#2983ff",
  "#1563fe", // official brand color
  "#0b4aea",
  "#103dbd",
  "#143894",
] as const;

export const Theme = createTheme({
  other: {},
  fontFamily: "Figtree, sans-serif",
  primaryShade: { light: 6, dark: 8 },

  /**
   * This is the color that Mantine will use as the default for UI elements
   * like buttons, links, or headlines.
   */
  primaryColor: "primary",
  colors: {
    /**
     * Our primary brand color.
     * Scale generated by uicolors.app with #1563fe as the base
     */
    primary: AVANDAR_BLUE_SHADES,

    /**
     * Supporting or accent color. Use sparingly to accent UI elements
     * like buttons, links, or headlines.
     */
    secondary: [
      "#fefbf1",
      "#fdf3d6",
      "#fcebbb",
      "#fbe3a0",
      "#fadb85",
      "#f8d36a",
      "#f7c948",
      "#de911d",
      "#b44d12",
      "#8d2b0b",
    ] as const,

    /** Positive states, E.g. completed, passed, saved */
    success: [
      "#eafcef",
      "#d9f6df",
      "#b1ebbe",
      "#86e09a",
      "#63d77c",
      "#4dd269",
      "#40cf5e",
      "#31b74e",
      "#27a343",
      "#168d36",
    ] as const,

    /** Warning states, E.g. approaching limits, risky actions */
    warning: [
      "#fffae2",
      "#fdf4ce",
      "#fae8a0",
      "#f6db6d",
      "#f4d043",
      "#f2c928",
      "#f1c617",
      "#d7ae06",
      "#bf9b00",
      "#a58500",
    ] as const,

    /** Negative states, E.g. errors, failed, deleted, invalid */
    danger: [
      "#ffebe8",
      "#ffd6d2",
      "#f6ada5",
      "#ef8075",
      "#e95a4c",
      "#e64231",
      "#e53523",
      "#cb2717",
      "#b61f13",
      "#a0140c",
    ] as const,

    /** Informational or neutral content (tooltips, messages) */
    info: [
      "#e6fcff",
      "#d5f5fa",
      "#abe9f3",
      "#7edcec",
      "#5dd2e6",
      "#49cce2",
      "#3bc9e1",
      "#2bb1c8",
      "#169eb3",
      "#00899d",
    ] as const,

    /** Background colors, E.g. app background, cards, panels */
    background: [
      "#f6f6f6",
      "#e7e7e7",
      "#d1d1d1",
      "#b0b0b0",
      "#888888",
      "#6d6d6d",
      "#5d5d5d",
      "#4f4f4f",
      "#454545",
      "#373737",
    ] as const,

    /** Secondary text, hints, descriptions */
    muted: [
      "#f6f6f6",
      "#e7e7e7",
      "#d1d1d1",
      "#b0b0b0",
      "#888888",
      "#666666",
      "#5d5d5d",
      "#4f4f4f",
      "#454545",
      "#3d3d3d",
    ] as const,

    /** Neutral lines, separators */
    border: [
      "#f6f6f6",
      "#e7e7e7",
      "#d1d1d1",
      "#b0b0b0",
      "#909090",
      "#6d6d6d",
      "#5d5d5d",
      "#4f4f4f",
      "#454545",
      "#3d3d3d",
    ] as const,
  },
});
