import { createTheme } from "@mantine/core";
import { QueryClient } from "@tanstack/react-query";

/**
 * Our primary brand color.
 * The scale is generated by uicolors.app with #1563fe as the base
 */
const AVANDAR_BLUE_SHADES = [
  "#edf6ff",
  "#d8ebff",
  "#b9dcff",
  "#89c7ff",
  "#51a7ff",
  "#2983ff",
  "#1563fe", // primary color
  "#0b4aea",
  "#103dbd",
  "#143894",
  "#11245a",
] as const;

const PRIMARY_SHADE = 6;

const QUERY_CLIENT = new QueryClient();

export const Theme = createTheme({
  colors: {
    "avandar-blue": AVANDAR_BLUE_SHADES,
  },
  fontFamily: "Figtree, sans-serif",
  primaryShade: PRIMARY_SHADE,
  primaryColor: "avandar-blue",
});
