import { propEq } from "@utils";
import { createAppStateManager } from "@/lib/utils/state/createAppStateManager/createAppStateManager";
import type { AvaPageData } from "@/views/DashboardApp/AvaPage/AvaPage.types";

export type DashboardEditorPendingBlock = {
  /**
   * The block payload to append to the active dashboard's content. We carry
   * the raw `unknown` shape because Puck doesn't expose a fully-typed
   * "ContentItem" type in our @puckeditor/core version.
   */
  block: AvaPageData["content"][number];
  /** Stable id from the LLM so duplicate emits can be de-duplicated. */
  pendingId: string;
  /**
   * The dashboard this block was generated for (from the chat page context).
   * Lets a block queued before the editor registers be flushed onto the
   * correct dashboard and dropped when a different dashboard becomes active.
   * `undefined` means "whatever dashboard is active", which preserves the
   * behavior of callers that don't know the id.
   */
  dashboardId?: string | undefined;
};

export type DashboardEditorAppState = {
  /**
   * Set only when a dashboard editor is currently mounted. The chat panel
   * reads this to decide whether it can offer the "add block" tool to the
   * model and to attach the right metadata to the LLM call.
   */
  activeDashboardId: string | undefined;

  /** Current in-memory Puck data for the active editor. */
  editorData: AvaPageData | undefined;

  /** Changes not yet persisted to the dashboard record. */
  hasUnsavedChanges: boolean;

  /** Revision used to remount Puck when a different dashboard is loaded. */
  editorRevision: number;

  /** Generated block ids already appended to the active dashboard. */
  appendedBlockIds: readonly string[];

  /**
   * Chat-generated blocks that arrived before the editor was ready to receive
   * them (e.g. the heavy Puck editor route is still mounting, so
   * `setActiveDashboard` has not run yet). They are held here instead of being
   * dropped, and flushed onto the content the moment the matching dashboard
   * registers itself as active. Kept across the register cycle (including
   * React StrictMode's mount → unmount → mount) so the flushed block is not
   * lost, and cleared per-block once it is absorbed into `editorData`.
   */
  pendingBlocks: readonly DashboardEditorPendingBlock[];
};

const INITIAL_STATE: DashboardEditorAppState = {
  activeDashboardId: undefined,
  editorData: undefined,
  hasUnsavedChanges: false,
  editorRevision: 0,
  appendedBlockIds: [],
  pendingBlocks: [],
};

/** Reads the stable Puck content-item id used to de-duplicate blocks. */
function _getBlockId(block: AvaPageData["content"][number]): string | undefined {
  const id: unknown = (block as { props?: { id?: unknown } }).props?.id;
  return typeof id === "string" ? id : undefined;
}

/** True when `content` already contains a block with the given id. */
function _contentHasBlockId(
  content: AvaPageData["content"] | undefined,
  blockId: string | undefined,
): boolean {
  if (!content || blockId === undefined) {
    return false;
  }
  return content.some((item) => {
    return _getBlockId(item) === blockId;
  });
}

/**
 * Appends the given pending blocks onto `content`, skipping any whose stable id
 * is already present. Returns the merged content and the list of pending ids
 * that were applied (for the de-dup guard).
 */
function _mergePendingBlocks(options: {
  content: AvaPageData["content"];
  pendingBlocks: readonly DashboardEditorPendingBlock[];
}): {
  content: AvaPageData["content"];
  appliedPendingIds: string[];
} {
  // De-dup reads the growing content, so appending is an order-dependent fold:
  // push onto a single accumulator (O(n)) rather than spreading it each step.
  const content = [...options.content];
  options.pendingBlocks.forEach((pending) => {
    if (!_contentHasBlockId(content, _getBlockId(pending.block))) {
      content.push(pending.block);
    }
  });
  const appliedPendingIds = options.pendingBlocks.map((pending) => {
    return pending.pendingId;
  });
  return { content, appliedPendingIds };
}

/**
 * Workspace-scoped state for the currently-active dashboard editor. Lets the
 * chat panel push generated P-blocks into the dashboard without depending on
 * the editor instance directly. Mounted at the WorkspaceLayout so any
 * dashboard route can populate it.
 */
export const DashboardEditorStateManager = createAppStateManager({
  name: "DashboardEditor",
  initialState: INITIAL_STATE,
  actions: {
    /**
     * Register the dashboard whose editor is currently visible. Called by
     * `DashboardEditorView` on mount and on dashboard id change.
     *
     * Flushes any `pendingBlocks` targeting this dashboard onto the initial
     * content so a block generated by chat before the editor finished mounting
     * still reaches the canvas. Pending blocks for a *different* dashboard are
     * dropped here; pending blocks are retained across an `undefined`
     * (unmount / StrictMode cleanup) transition so the following remount can
     * re-flush them.
     */
    setActiveDashboard: (
      state: DashboardEditorAppState,
      activeDashboard:
        | { dashboardId: string; editorData: AvaPageData }
        | undefined,
    ): DashboardEditorAppState => {
      if (state.activeDashboardId === activeDashboard?.dashboardId) {
        return state;
      }

      if (!activeDashboard) {
        return {
          ...state,
          activeDashboardId: undefined,
          editorData: undefined,
          hasUnsavedChanges: false,
          editorRevision: state.editorRevision + 1,
          appendedBlockIds: [],
          // Keep pending blocks: an `undefined` transition is either a
          // StrictMode cleanup (immediately followed by a remount) or a real
          // unmount. In both cases the next dashboard's `setActiveDashboard`
          // decides what to keep, so nothing is lost here.
        };
      }

      const pendingForThisDashboard = state.pendingBlocks.filter((pending) => {
        return (
          pending.dashboardId === undefined ||
          pending.dashboardId === activeDashboard.dashboardId
        );
      });
      const { content, appliedPendingIds } = _mergePendingBlocks({
        content: activeDashboard.editorData.content ?? [],
        pendingBlocks: pendingForThisDashboard,
      });

      return {
        ...state,
        activeDashboardId: activeDashboard.dashboardId,
        editorData: { ...activeDashboard.editorData, content },
        hasUnsavedChanges: appliedPendingIds.length > 0,
        editorRevision: state.editorRevision + 1,
        appendedBlockIds: appliedPendingIds,
        // Retain only the pending blocks for this dashboard; a block queued for
        // a different dashboard is no longer relevant once we switch.
        pendingBlocks: pendingForThisDashboard,
      };
    },

    /**
     * Append a generated block to the active editor's Puck data and bump
     * `editorRevision`. Puck seeds its internal store from the `data` prop only
     * on mount, so appending to `editorData` alone would not reach the canvas
     * or Save (both read Puck's store). Bumping the revision remounts Puck
     * with the appended block, keeping the two in agreement: an appended block
     * is both visible on the canvas and persisted by Save.
     *
     * If the editor has not registered yet (`editorData` is still `undefined`),
     * the block is buffered in `pendingBlocks` instead of being dropped, and
     * `setActiveDashboard` flushes it once the editor mounts.
     */
    queuePendingBlock: (
      state: DashboardEditorAppState,
      block: DashboardEditorPendingBlock,
    ): DashboardEditorAppState => {
      const alreadyAppended = state.appendedBlockIds.includes(block.pendingId);
      const alreadyBuffered = state.pendingBlocks.some(
        propEq("pendingId", block.pendingId),
      );
      if (alreadyAppended || alreadyBuffered) {
        return state;
      }

      const targetsActiveDashboard =
        block.dashboardId === undefined ||
        block.dashboardId === state.activeDashboardId;

      // Fast path: the editor is registered and this block targets it, so
      // append directly and remount Puck via the revision bump.
      if (state.editorData && targetsActiveDashboard) {
        return {
          ...state,
          editorData: {
            ...state.editorData,
            content: [...(state.editorData.content ?? []), block.block],
          },
          hasUnsavedChanges: true,
          editorRevision: state.editorRevision + 1,
          appendedBlockIds: [...state.appendedBlockIds, block.pendingId],
        };
      }

      // The editor is not ready (or the block targets a not-yet-active
      // dashboard). Buffer it so `setActiveDashboard` can flush it on mount.
      return {
        ...state,
        pendingBlocks: [...state.pendingBlocks, block],
      };
    },

    /** Replace the active Puck data after an editor interaction. */
    updateEditorData: (
      state: DashboardEditorAppState,
      editorData: AvaPageData,
    ): DashboardEditorAppState => {
      // Absorb: once a buffered block is present in the editor's own data it is
      // owned by Puck, so drop it from the buffer to prevent it re-appearing on
      // a later remount (e.g. after the user deletes it).
      const remainingPending = state.pendingBlocks.filter((pending) => {
        const blockId = _getBlockId(pending.block);
        return !_contentHasBlockId(editorData.content, blockId);
      });
      return {
        ...state,
        editorData,
        hasUnsavedChanges: true,
        pendingBlocks: remainingPending,
      };
    },

    /** Mark the current editor data as persisted. */
    markSaved: (state: DashboardEditorAppState): DashboardEditorAppState => {
      // Everything mounted has been persisted, so any remaining buffered blocks
      // are now saved too (or belong to a dashboard we're not editing).
      return { ...state, hasUnsavedChanges: false, pendingBlocks: [] };
    },
  },
});
