/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as UpdatePasswordRouteImport } from "./routes/update-password";
import { Route as SigninRouteImport } from "./routes/signin";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password";
import { Route as AuthRouteRouteImport } from "./routes/_auth/route";
import { Route as DSlugOrIdRouteImport } from "./routes/d/$slugOrId";
import { Route as AuthnoWorkspaceRouteRouteImport } from "./routes/_auth/(no-workspace)/route";
import { Route as AuthWorkspaceSlugRouteRouteImport } from "./routes/_auth/$workspaceSlug/route";
import { Route as AuthnoWorkspaceIndexRouteImport } from "./routes/_auth/(no-workspace)/index";
import { Route as AuthWorkspaceSlugIndexRouteImport } from "./routes/_auth/$workspaceSlug/index";
import { Route as AuthnoWorkspaceInvalidWorkspaceRouteImport } from "./routes/_auth/(no-workspace)/invalid-workspace";
import { Route as AuthWorkspaceSlugProfileRouteImport } from "./routes/_auth/$workspaceSlug/profile";
import { Route as AuthWorkspaceSlugMapRouteImport } from "./routes/_auth/$workspaceSlug/map";
import { Route as AuthWorkspaceSlugDataExplorerRouteImport } from "./routes/_auth/$workspaceSlug/data-explorer";
import { Route as AuthWorkspaceSlugCheckoutRouteImport } from "./routes/_auth/$workspaceSlug/checkout";
import { Route as AuthWorkspaceSlugAccessDeniedRouteImport } from "./routes/_auth/$workspaceSlug/access-denied";
import { Route as AuthWorkspaceSlugSettingsRouteRouteImport } from "./routes/_auth/$workspaceSlug/settings/route";
import { Route as AuthWorkspaceSlugOntologyDesignerRouteRouteImport } from "./routes/_auth/$workspaceSlug/ontology-designer/route";
import { Route as AuthWorkspaceSlugDataManagerRouteRouteImport } from "./routes/_auth/$workspaceSlug/data-manager/route";
import { Route as AuthWorkspaceSlugDashboardsRouteRouteImport } from "./routes/_auth/$workspaceSlug/dashboards/route";
import { Route as AuthWorkspaceSlugSettingsIndexRouteImport } from "./routes/_auth/$workspaceSlug/settings/index";
import { Route as AuthWorkspaceSlugOntologyDesignerIndexRouteImport } from "./routes/_auth/$workspaceSlug/ontology-designer/index";
import { Route as AuthWorkspaceSlugIndividualManagerIndexRouteImport } from "./routes/_auth/$workspaceSlug/individual-manager/index";
import { Route as AuthWorkspaceSlugDataManagerIndexRouteImport } from "./routes/_auth/$workspaceSlug/data-manager/index";
import { Route as AuthWorkspaceSlugDashboardsIndexRouteImport } from "./routes/_auth/$workspaceSlug/dashboards/index";
import { Route as PublicDashboardsWorkspaceSlugDashboardIdRouteImport } from "./routes/public/dashboards/$workspaceSlug/$dashboardId";
import { Route as AuthnoWorkspaceInvitesInviteIdRouteImport } from "./routes/_auth/(no-workspace)/invites/$inviteId";
import { Route as AuthWorkspaceSlugSettingsTabNameRouteImport } from "./routes/_auth/$workspaceSlug/settings/$tabName";
import { Route as AuthWorkspaceSlugOntologyDesignerConceptCreatorRouteImport } from "./routes/_auth/$workspaceSlug/ontology-designer/concept-creator";
import { Route as AuthWorkspaceSlugOntologyDesignerConceptIdRouteImport } from "./routes/_auth/$workspaceSlug/ontology-designer/$conceptId";
import { Route as AuthWorkspaceSlugDataManagerDataImportRouteImport } from "./routes/_auth/$workspaceSlug/data-manager/data-import";
import { Route as AuthWorkspaceSlugDataManagerDatasetIdRouteImport } from "./routes/_auth/$workspaceSlug/data-manager/$datasetId";
import { Route as AuthWorkspaceSlugDSlugOrIdRouteImport } from "./routes/_auth/$workspaceSlug/d/$slugOrId";
import { Route as AuthWorkspaceSlugIndividualManagerConceptIdRouteRouteImport } from "./routes/_auth/$workspaceSlug/individual-manager/$conceptId/route";
import { Route as AuthWorkspaceSlugIndividualManagerConceptIdIndexRouteImport } from "./routes/_auth/$workspaceSlug/individual-manager/$conceptId/index";
import { Route as AuthWorkspaceSlugIndividualManagerConceptIdIndividualIdRouteImport } from "./routes/_auth/$workspaceSlug/individual-manager/$conceptId/$individualId";
import { Route as AuthWorkspaceSlugDashboardsPreviewDashboardIdRouteImport } from "./routes/_auth/$workspaceSlug/dashboards/preview/$dashboardId";
import { Route as AuthWorkspaceSlugDashboardsEditDashboardIdRouteImport } from "./routes/_auth/$workspaceSlug/dashboards/edit/$dashboardId";

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: "/update-password",
  path: "/update-password",
  getParentRoute: () => rootRouteImport,
} as any);
const SigninRoute = SigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const DSlugOrIdRoute = DSlugOrIdRouteImport.update({
  id: "/d/$slugOrId",
  path: "/d/$slugOrId",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthnoWorkspaceRouteRoute = AuthnoWorkspaceRouteRouteImport.update({
  id: "/(no-workspace)",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthWorkspaceSlugRouteRoute = AuthWorkspaceSlugRouteRouteImport.update({
  id: "/$workspaceSlug",
  path: "/$workspaceSlug",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthnoWorkspaceIndexRoute = AuthnoWorkspaceIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthnoWorkspaceRouteRoute,
} as any);
const AuthWorkspaceSlugIndexRoute = AuthWorkspaceSlugIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthWorkspaceSlugRouteRoute,
} as any);
const AuthnoWorkspaceInvalidWorkspaceRoute =
  AuthnoWorkspaceInvalidWorkspaceRouteImport.update({
    id: "/invalid-workspace",
    path: "/invalid-workspace",
    getParentRoute: () => AuthnoWorkspaceRouteRoute,
  } as any);
const AuthWorkspaceSlugProfileRoute =
  AuthWorkspaceSlugProfileRouteImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => AuthWorkspaceSlugRouteRoute,
  } as any);
const AuthWorkspaceSlugMapRoute = AuthWorkspaceSlugMapRouteImport.update({
  id: "/map",
  path: "/map",
  getParentRoute: () => AuthWorkspaceSlugRouteRoute,
} as any);
const AuthWorkspaceSlugDataExplorerRoute =
  AuthWorkspaceSlugDataExplorerRouteImport.update({
    id: "/data-explorer",
    path: "/data-explorer",
    getParentRoute: () => AuthWorkspaceSlugRouteRoute,
  } as any);
const AuthWorkspaceSlugCheckoutRoute =
  AuthWorkspaceSlugCheckoutRouteImport.update({
    id: "/checkout",
    path: "/checkout",
    getParentRoute: () => AuthWorkspaceSlugRouteRoute,
  } as any);
const AuthWorkspaceSlugAccessDeniedRoute =
  AuthWorkspaceSlugAccessDeniedRouteImport.update({
    id: "/access-denied",
    path: "/access-denied",
    getParentRoute: () => AuthWorkspaceSlugRouteRoute,
  } as any);
const AuthWorkspaceSlugSettingsRouteRoute =
  AuthWorkspaceSlugSettingsRouteRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => AuthWorkspaceSlugRouteRoute,
  } as any);
const AuthWorkspaceSlugOntologyDesignerRouteRoute =
  AuthWorkspaceSlugOntologyDesignerRouteRouteImport.update({
    id: "/ontology-designer",
    path: "/ontology-designer",
    getParentRoute: () => AuthWorkspaceSlugRouteRoute,
  } as any);
const AuthWorkspaceSlugDataManagerRouteRoute =
  AuthWorkspaceSlugDataManagerRouteRouteImport.update({
    id: "/data-manager",
    path: "/data-manager",
    getParentRoute: () => AuthWorkspaceSlugRouteRoute,
  } as any);
const AuthWorkspaceSlugDashboardsRouteRoute =
  AuthWorkspaceSlugDashboardsRouteRouteImport.update({
    id: "/dashboards",
    path: "/dashboards",
    getParentRoute: () => AuthWorkspaceSlugRouteRoute,
  } as any);
const AuthWorkspaceSlugSettingsIndexRoute =
  AuthWorkspaceSlugSettingsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthWorkspaceSlugSettingsRouteRoute,
  } as any);
const AuthWorkspaceSlugOntologyDesignerIndexRoute =
  AuthWorkspaceSlugOntologyDesignerIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthWorkspaceSlugOntologyDesignerRouteRoute,
  } as any);
const AuthWorkspaceSlugIndividualManagerIndexRoute =
  AuthWorkspaceSlugIndividualManagerIndexRouteImport.update({
    id: "/individual-manager/",
    path: "/individual-manager/",
    getParentRoute: () => AuthWorkspaceSlugRouteRoute,
  } as any);
const AuthWorkspaceSlugDataManagerIndexRoute =
  AuthWorkspaceSlugDataManagerIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthWorkspaceSlugDataManagerRouteRoute,
  } as any);
const AuthWorkspaceSlugDashboardsIndexRoute =
  AuthWorkspaceSlugDashboardsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthWorkspaceSlugDashboardsRouteRoute,
  } as any);
const PublicDashboardsWorkspaceSlugDashboardIdRoute =
  PublicDashboardsWorkspaceSlugDashboardIdRouteImport.update({
    id: "/public/dashboards/$workspaceSlug/$dashboardId",
    path: "/public/dashboards/$workspaceSlug/$dashboardId",
    getParentRoute: () => rootRouteImport,
  } as any);
const AuthnoWorkspaceInvitesInviteIdRoute =
  AuthnoWorkspaceInvitesInviteIdRouteImport.update({
    id: "/invites/$inviteId",
    path: "/invites/$inviteId",
    getParentRoute: () => AuthnoWorkspaceRouteRoute,
  } as any);
const AuthWorkspaceSlugSettingsTabNameRoute =
  AuthWorkspaceSlugSettingsTabNameRouteImport.update({
    id: "/$tabName",
    path: "/$tabName",
    getParentRoute: () => AuthWorkspaceSlugSettingsRouteRoute,
  } as any);
const AuthWorkspaceSlugOntologyDesignerConceptCreatorRoute =
  AuthWorkspaceSlugOntologyDesignerConceptCreatorRouteImport.update({
    id: "/concept-creator",
    path: "/concept-creator",
    getParentRoute: () => AuthWorkspaceSlugOntologyDesignerRouteRoute,
  } as any);
const AuthWorkspaceSlugOntologyDesignerConceptIdRoute =
  AuthWorkspaceSlugOntologyDesignerConceptIdRouteImport.update({
    id: "/$conceptId",
    path: "/$conceptId",
    getParentRoute: () => AuthWorkspaceSlugOntologyDesignerRouteRoute,
  } as any);
const AuthWorkspaceSlugDataManagerDataImportRoute =
  AuthWorkspaceSlugDataManagerDataImportRouteImport.update({
    id: "/data-import",
    path: "/data-import",
    getParentRoute: () => AuthWorkspaceSlugDataManagerRouteRoute,
  } as any);
const AuthWorkspaceSlugDataManagerDatasetIdRoute =
  AuthWorkspaceSlugDataManagerDatasetIdRouteImport.update({
    id: "/$datasetId",
    path: "/$datasetId",
    getParentRoute: () => AuthWorkspaceSlugDataManagerRouteRoute,
  } as any);
const AuthWorkspaceSlugDSlugOrIdRoute =
  AuthWorkspaceSlugDSlugOrIdRouteImport.update({
    id: "/d/$slugOrId",
    path: "/d/$slugOrId",
    getParentRoute: () => AuthWorkspaceSlugRouteRoute,
  } as any);
const AuthWorkspaceSlugIndividualManagerConceptIdRouteRoute =
  AuthWorkspaceSlugIndividualManagerConceptIdRouteRouteImport.update({
    id: "/individual-manager/$conceptId",
    path: "/individual-manager/$conceptId",
    getParentRoute: () => AuthWorkspaceSlugRouteRoute,
  } as any);
const AuthWorkspaceSlugIndividualManagerConceptIdIndexRoute =
  AuthWorkspaceSlugIndividualManagerConceptIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthWorkspaceSlugIndividualManagerConceptIdRouteRoute,
  } as any);
const AuthWorkspaceSlugIndividualManagerConceptIdIndividualIdRoute =
  AuthWorkspaceSlugIndividualManagerConceptIdIndividualIdRouteImport.update({
    id: "/$individualId",
    path: "/$individualId",
    getParentRoute: () => AuthWorkspaceSlugIndividualManagerConceptIdRouteRoute,
  } as any);
const AuthWorkspaceSlugDashboardsPreviewDashboardIdRoute =
  AuthWorkspaceSlugDashboardsPreviewDashboardIdRouteImport.update({
    id: "/preview/$dashboardId",
    path: "/preview/$dashboardId",
    getParentRoute: () => AuthWorkspaceSlugDashboardsRouteRoute,
  } as any);
const AuthWorkspaceSlugDashboardsEditDashboardIdRoute =
  AuthWorkspaceSlugDashboardsEditDashboardIdRouteImport.update({
    id: "/edit/$dashboardId",
    path: "/edit/$dashboardId",
    getParentRoute: () => AuthWorkspaceSlugDashboardsRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthnoWorkspaceIndexRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/register": typeof RegisterRoute;
  "/signin": typeof SigninRoute;
  "/update-password": typeof UpdatePasswordRoute;
  "/$workspaceSlug": typeof AuthWorkspaceSlugRouteRouteWithChildren;
  "/d/$slugOrId": typeof DSlugOrIdRoute;
  "/$workspaceSlug/dashboards": typeof AuthWorkspaceSlugDashboardsRouteRouteWithChildren;
  "/$workspaceSlug/data-manager": typeof AuthWorkspaceSlugDataManagerRouteRouteWithChildren;
  "/$workspaceSlug/ontology-designer": typeof AuthWorkspaceSlugOntologyDesignerRouteRouteWithChildren;
  "/$workspaceSlug/settings": typeof AuthWorkspaceSlugSettingsRouteRouteWithChildren;
  "/$workspaceSlug/access-denied": typeof AuthWorkspaceSlugAccessDeniedRoute;
  "/$workspaceSlug/checkout": typeof AuthWorkspaceSlugCheckoutRoute;
  "/$workspaceSlug/data-explorer": typeof AuthWorkspaceSlugDataExplorerRoute;
  "/$workspaceSlug/map": typeof AuthWorkspaceSlugMapRoute;
  "/$workspaceSlug/profile": typeof AuthWorkspaceSlugProfileRoute;
  "/invalid-workspace": typeof AuthnoWorkspaceInvalidWorkspaceRoute;
  "/$workspaceSlug/": typeof AuthWorkspaceSlugIndexRoute;
  "/$workspaceSlug/individual-manager/$conceptId": typeof AuthWorkspaceSlugIndividualManagerConceptIdRouteRouteWithChildren;
  "/$workspaceSlug/d/$slugOrId": typeof AuthWorkspaceSlugDSlugOrIdRoute;
  "/$workspaceSlug/data-manager/$datasetId": typeof AuthWorkspaceSlugDataManagerDatasetIdRoute;
  "/$workspaceSlug/data-manager/data-import": typeof AuthWorkspaceSlugDataManagerDataImportRoute;
  "/$workspaceSlug/ontology-designer/$conceptId": typeof AuthWorkspaceSlugOntologyDesignerConceptIdRoute;
  "/$workspaceSlug/ontology-designer/concept-creator": typeof AuthWorkspaceSlugOntologyDesignerConceptCreatorRoute;
  "/$workspaceSlug/settings/$tabName": typeof AuthWorkspaceSlugSettingsTabNameRoute;
  "/invites/$inviteId": typeof AuthnoWorkspaceInvitesInviteIdRoute;
  "/public/dashboards/$workspaceSlug/$dashboardId": typeof PublicDashboardsWorkspaceSlugDashboardIdRoute;
  "/$workspaceSlug/dashboards/": typeof AuthWorkspaceSlugDashboardsIndexRoute;
  "/$workspaceSlug/data-manager/": typeof AuthWorkspaceSlugDataManagerIndexRoute;
  "/$workspaceSlug/individual-manager/": typeof AuthWorkspaceSlugIndividualManagerIndexRoute;
  "/$workspaceSlug/ontology-designer/": typeof AuthWorkspaceSlugOntologyDesignerIndexRoute;
  "/$workspaceSlug/settings/": typeof AuthWorkspaceSlugSettingsIndexRoute;
  "/$workspaceSlug/dashboards/edit/$dashboardId": typeof AuthWorkspaceSlugDashboardsEditDashboardIdRoute;
  "/$workspaceSlug/dashboards/preview/$dashboardId": typeof AuthWorkspaceSlugDashboardsPreviewDashboardIdRoute;
  "/$workspaceSlug/individual-manager/$conceptId/$individualId": typeof AuthWorkspaceSlugIndividualManagerConceptIdIndividualIdRoute;
  "/$workspaceSlug/individual-manager/$conceptId/": typeof AuthWorkspaceSlugIndividualManagerConceptIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof AuthnoWorkspaceIndexRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/register": typeof RegisterRoute;
  "/signin": typeof SigninRoute;
  "/update-password": typeof UpdatePasswordRoute;
  "/d/$slugOrId": typeof DSlugOrIdRoute;
  "/$workspaceSlug/access-denied": typeof AuthWorkspaceSlugAccessDeniedRoute;
  "/$workspaceSlug/checkout": typeof AuthWorkspaceSlugCheckoutRoute;
  "/$workspaceSlug/data-explorer": typeof AuthWorkspaceSlugDataExplorerRoute;
  "/$workspaceSlug/map": typeof AuthWorkspaceSlugMapRoute;
  "/$workspaceSlug/profile": typeof AuthWorkspaceSlugProfileRoute;
  "/invalid-workspace": typeof AuthnoWorkspaceInvalidWorkspaceRoute;
  "/$workspaceSlug": typeof AuthWorkspaceSlugIndexRoute;
  "/$workspaceSlug/d/$slugOrId": typeof AuthWorkspaceSlugDSlugOrIdRoute;
  "/$workspaceSlug/data-manager/$datasetId": typeof AuthWorkspaceSlugDataManagerDatasetIdRoute;
  "/$workspaceSlug/data-manager/data-import": typeof AuthWorkspaceSlugDataManagerDataImportRoute;
  "/$workspaceSlug/ontology-designer/$conceptId": typeof AuthWorkspaceSlugOntologyDesignerConceptIdRoute;
  "/$workspaceSlug/ontology-designer/concept-creator": typeof AuthWorkspaceSlugOntologyDesignerConceptCreatorRoute;
  "/$workspaceSlug/settings/$tabName": typeof AuthWorkspaceSlugSettingsTabNameRoute;
  "/invites/$inviteId": typeof AuthnoWorkspaceInvitesInviteIdRoute;
  "/public/dashboards/$workspaceSlug/$dashboardId": typeof PublicDashboardsWorkspaceSlugDashboardIdRoute;
  "/$workspaceSlug/dashboards": typeof AuthWorkspaceSlugDashboardsIndexRoute;
  "/$workspaceSlug/data-manager": typeof AuthWorkspaceSlugDataManagerIndexRoute;
  "/$workspaceSlug/individual-manager": typeof AuthWorkspaceSlugIndividualManagerIndexRoute;
  "/$workspaceSlug/ontology-designer": typeof AuthWorkspaceSlugOntologyDesignerIndexRoute;
  "/$workspaceSlug/settings": typeof AuthWorkspaceSlugSettingsIndexRoute;
  "/$workspaceSlug/dashboards/edit/$dashboardId": typeof AuthWorkspaceSlugDashboardsEditDashboardIdRoute;
  "/$workspaceSlug/dashboards/preview/$dashboardId": typeof AuthWorkspaceSlugDashboardsPreviewDashboardIdRoute;
  "/$workspaceSlug/individual-manager/$conceptId/$individualId": typeof AuthWorkspaceSlugIndividualManagerConceptIdIndividualIdRoute;
  "/$workspaceSlug/individual-manager/$conceptId": typeof AuthWorkspaceSlugIndividualManagerConceptIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_auth": typeof AuthRouteRouteWithChildren;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/register": typeof RegisterRoute;
  "/signin": typeof SigninRoute;
  "/update-password": typeof UpdatePasswordRoute;
  "/_auth/$workspaceSlug": typeof AuthWorkspaceSlugRouteRouteWithChildren;
  "/_auth/(no-workspace)": typeof AuthnoWorkspaceRouteRouteWithChildren;
  "/d/$slugOrId": typeof DSlugOrIdRoute;
  "/_auth/$workspaceSlug/dashboards": typeof AuthWorkspaceSlugDashboardsRouteRouteWithChildren;
  "/_auth/$workspaceSlug/data-manager": typeof AuthWorkspaceSlugDataManagerRouteRouteWithChildren;
  "/_auth/$workspaceSlug/ontology-designer": typeof AuthWorkspaceSlugOntologyDesignerRouteRouteWithChildren;
  "/_auth/$workspaceSlug/settings": typeof AuthWorkspaceSlugSettingsRouteRouteWithChildren;
  "/_auth/$workspaceSlug/access-denied": typeof AuthWorkspaceSlugAccessDeniedRoute;
  "/_auth/$workspaceSlug/checkout": typeof AuthWorkspaceSlugCheckoutRoute;
  "/_auth/$workspaceSlug/data-explorer": typeof AuthWorkspaceSlugDataExplorerRoute;
  "/_auth/$workspaceSlug/map": typeof AuthWorkspaceSlugMapRoute;
  "/_auth/$workspaceSlug/profile": typeof AuthWorkspaceSlugProfileRoute;
  "/_auth/(no-workspace)/invalid-workspace": typeof AuthnoWorkspaceInvalidWorkspaceRoute;
  "/_auth/$workspaceSlug/": typeof AuthWorkspaceSlugIndexRoute;
  "/_auth/(no-workspace)/": typeof AuthnoWorkspaceIndexRoute;
  "/_auth/$workspaceSlug/individual-manager/$conceptId": typeof AuthWorkspaceSlugIndividualManagerConceptIdRouteRouteWithChildren;
  "/_auth/$workspaceSlug/d/$slugOrId": typeof AuthWorkspaceSlugDSlugOrIdRoute;
  "/_auth/$workspaceSlug/data-manager/$datasetId": typeof AuthWorkspaceSlugDataManagerDatasetIdRoute;
  "/_auth/$workspaceSlug/data-manager/data-import": typeof AuthWorkspaceSlugDataManagerDataImportRoute;
  "/_auth/$workspaceSlug/ontology-designer/$conceptId": typeof AuthWorkspaceSlugOntologyDesignerConceptIdRoute;
  "/_auth/$workspaceSlug/ontology-designer/concept-creator": typeof AuthWorkspaceSlugOntologyDesignerConceptCreatorRoute;
  "/_auth/$workspaceSlug/settings/$tabName": typeof AuthWorkspaceSlugSettingsTabNameRoute;
  "/_auth/(no-workspace)/invites/$inviteId": typeof AuthnoWorkspaceInvitesInviteIdRoute;
  "/public/dashboards/$workspaceSlug/$dashboardId": typeof PublicDashboardsWorkspaceSlugDashboardIdRoute;
  "/_auth/$workspaceSlug/dashboards/": typeof AuthWorkspaceSlugDashboardsIndexRoute;
  "/_auth/$workspaceSlug/data-manager/": typeof AuthWorkspaceSlugDataManagerIndexRoute;
  "/_auth/$workspaceSlug/individual-manager/": typeof AuthWorkspaceSlugIndividualManagerIndexRoute;
  "/_auth/$workspaceSlug/ontology-designer/": typeof AuthWorkspaceSlugOntologyDesignerIndexRoute;
  "/_auth/$workspaceSlug/settings/": typeof AuthWorkspaceSlugSettingsIndexRoute;
  "/_auth/$workspaceSlug/dashboards/edit/$dashboardId": typeof AuthWorkspaceSlugDashboardsEditDashboardIdRoute;
  "/_auth/$workspaceSlug/dashboards/preview/$dashboardId": typeof AuthWorkspaceSlugDashboardsPreviewDashboardIdRoute;
  "/_auth/$workspaceSlug/individual-manager/$conceptId/$individualId": typeof AuthWorkspaceSlugIndividualManagerConceptIdIndividualIdRoute;
  "/_auth/$workspaceSlug/individual-manager/$conceptId/": typeof AuthWorkspaceSlugIndividualManagerConceptIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/forgot-password"
    | "/register"
    | "/signin"
    | "/update-password"
    | "/$workspaceSlug"
    | "/d/$slugOrId"
    | "/$workspaceSlug/dashboards"
    | "/$workspaceSlug/data-manager"
    | "/$workspaceSlug/ontology-designer"
    | "/$workspaceSlug/settings"
    | "/$workspaceSlug/access-denied"
    | "/$workspaceSlug/checkout"
    | "/$workspaceSlug/data-explorer"
    | "/$workspaceSlug/map"
    | "/$workspaceSlug/profile"
    | "/invalid-workspace"
    | "/$workspaceSlug/"
    | "/$workspaceSlug/individual-manager/$conceptId"
    | "/$workspaceSlug/d/$slugOrId"
    | "/$workspaceSlug/data-manager/$datasetId"
    | "/$workspaceSlug/data-manager/data-import"
    | "/$workspaceSlug/ontology-designer/$conceptId"
    | "/$workspaceSlug/ontology-designer/concept-creator"
    | "/$workspaceSlug/settings/$tabName"
    | "/invites/$inviteId"
    | "/public/dashboards/$workspaceSlug/$dashboardId"
    | "/$workspaceSlug/dashboards/"
    | "/$workspaceSlug/data-manager/"
    | "/$workspaceSlug/individual-manager/"
    | "/$workspaceSlug/ontology-designer/"
    | "/$workspaceSlug/settings/"
    | "/$workspaceSlug/dashboards/edit/$dashboardId"
    | "/$workspaceSlug/dashboards/preview/$dashboardId"
    | "/$workspaceSlug/individual-manager/$conceptId/$individualId"
    | "/$workspaceSlug/individual-manager/$conceptId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/forgot-password"
    | "/register"
    | "/signin"
    | "/update-password"
    | "/d/$slugOrId"
    | "/$workspaceSlug/access-denied"
    | "/$workspaceSlug/checkout"
    | "/$workspaceSlug/data-explorer"
    | "/$workspaceSlug/map"
    | "/$workspaceSlug/profile"
    | "/invalid-workspace"
    | "/$workspaceSlug"
    | "/$workspaceSlug/d/$slugOrId"
    | "/$workspaceSlug/data-manager/$datasetId"
    | "/$workspaceSlug/data-manager/data-import"
    | "/$workspaceSlug/ontology-designer/$conceptId"
    | "/$workspaceSlug/ontology-designer/concept-creator"
    | "/$workspaceSlug/settings/$tabName"
    | "/invites/$inviteId"
    | "/public/dashboards/$workspaceSlug/$dashboardId"
    | "/$workspaceSlug/dashboards"
    | "/$workspaceSlug/data-manager"
    | "/$workspaceSlug/individual-manager"
    | "/$workspaceSlug/ontology-designer"
    | "/$workspaceSlug/settings"
    | "/$workspaceSlug/dashboards/edit/$dashboardId"
    | "/$workspaceSlug/dashboards/preview/$dashboardId"
    | "/$workspaceSlug/individual-manager/$conceptId/$individualId"
    | "/$workspaceSlug/individual-manager/$conceptId";
  id:
    | "__root__"
    | "/_auth"
    | "/forgot-password"
    | "/register"
    | "/signin"
    | "/update-password"
    | "/_auth/$workspaceSlug"
    | "/_auth/(no-workspace)"
    | "/d/$slugOrId"
    | "/_auth/$workspaceSlug/dashboards"
    | "/_auth/$workspaceSlug/data-manager"
    | "/_auth/$workspaceSlug/ontology-designer"
    | "/_auth/$workspaceSlug/settings"
    | "/_auth/$workspaceSlug/access-denied"
    | "/_auth/$workspaceSlug/checkout"
    | "/_auth/$workspaceSlug/data-explorer"
    | "/_auth/$workspaceSlug/map"
    | "/_auth/$workspaceSlug/profile"
    | "/_auth/(no-workspace)/invalid-workspace"
    | "/_auth/$workspaceSlug/"
    | "/_auth/(no-workspace)/"
    | "/_auth/$workspaceSlug/individual-manager/$conceptId"
    | "/_auth/$workspaceSlug/d/$slugOrId"
    | "/_auth/$workspaceSlug/data-manager/$datasetId"
    | "/_auth/$workspaceSlug/data-manager/data-import"
    | "/_auth/$workspaceSlug/ontology-designer/$conceptId"
    | "/_auth/$workspaceSlug/ontology-designer/concept-creator"
    | "/_auth/$workspaceSlug/settings/$tabName"
    | "/_auth/(no-workspace)/invites/$inviteId"
    | "/public/dashboards/$workspaceSlug/$dashboardId"
    | "/_auth/$workspaceSlug/dashboards/"
    | "/_auth/$workspaceSlug/data-manager/"
    | "/_auth/$workspaceSlug/individual-manager/"
    | "/_auth/$workspaceSlug/ontology-designer/"
    | "/_auth/$workspaceSlug/settings/"
    | "/_auth/$workspaceSlug/dashboards/edit/$dashboardId"
    | "/_auth/$workspaceSlug/dashboards/preview/$dashboardId"
    | "/_auth/$workspaceSlug/individual-manager/$conceptId/$individualId"
    | "/_auth/$workspaceSlug/individual-manager/$conceptId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  RegisterRoute: typeof RegisterRoute;
  SigninRoute: typeof SigninRoute;
  UpdatePasswordRoute: typeof UpdatePasswordRoute;
  DSlugOrIdRoute: typeof DSlugOrIdRoute;
  PublicDashboardsWorkspaceSlugDashboardIdRoute: typeof PublicDashboardsWorkspaceSlugDashboardIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/update-password": {
      id: "/update-password";
      path: "/update-password";
      fullPath: "/update-password";
      preLoaderRoute: typeof UpdatePasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signin": {
      id: "/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof SigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/forgot-password": {
      id: "/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/d/$slugOrId": {
      id: "/d/$slugOrId";
      path: "/d/$slugOrId";
      fullPath: "/d/$slugOrId";
      preLoaderRoute: typeof DSlugOrIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/(no-workspace)": {
      id: "/_auth/(no-workspace)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthnoWorkspaceRouteRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/$workspaceSlug": {
      id: "/_auth/$workspaceSlug";
      path: "/$workspaceSlug";
      fullPath: "/$workspaceSlug";
      preLoaderRoute: typeof AuthWorkspaceSlugRouteRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/(no-workspace)/": {
      id: "/_auth/(no-workspace)/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthnoWorkspaceIndexRouteImport;
      parentRoute: typeof AuthnoWorkspaceRouteRoute;
    };
    "/_auth/$workspaceSlug/": {
      id: "/_auth/$workspaceSlug/";
      path: "/";
      fullPath: "/$workspaceSlug/";
      preLoaderRoute: typeof AuthWorkspaceSlugIndexRouteImport;
      parentRoute: typeof AuthWorkspaceSlugRouteRoute;
    };
    "/_auth/(no-workspace)/invalid-workspace": {
      id: "/_auth/(no-workspace)/invalid-workspace";
      path: "/invalid-workspace";
      fullPath: "/invalid-workspace";
      preLoaderRoute: typeof AuthnoWorkspaceInvalidWorkspaceRouteImport;
      parentRoute: typeof AuthnoWorkspaceRouteRoute;
    };
    "/_auth/$workspaceSlug/profile": {
      id: "/_auth/$workspaceSlug/profile";
      path: "/profile";
      fullPath: "/$workspaceSlug/profile";
      preLoaderRoute: typeof AuthWorkspaceSlugProfileRouteImport;
      parentRoute: typeof AuthWorkspaceSlugRouteRoute;
    };
    "/_auth/$workspaceSlug/map": {
      id: "/_auth/$workspaceSlug/map";
      path: "/map";
      fullPath: "/$workspaceSlug/map";
      preLoaderRoute: typeof AuthWorkspaceSlugMapRouteImport;
      parentRoute: typeof AuthWorkspaceSlugRouteRoute;
    };
    "/_auth/$workspaceSlug/data-explorer": {
      id: "/_auth/$workspaceSlug/data-explorer";
      path: "/data-explorer";
      fullPath: "/$workspaceSlug/data-explorer";
      preLoaderRoute: typeof AuthWorkspaceSlugDataExplorerRouteImport;
      parentRoute: typeof AuthWorkspaceSlugRouteRoute;
    };
    "/_auth/$workspaceSlug/checkout": {
      id: "/_auth/$workspaceSlug/checkout";
      path: "/checkout";
      fullPath: "/$workspaceSlug/checkout";
      preLoaderRoute: typeof AuthWorkspaceSlugCheckoutRouteImport;
      parentRoute: typeof AuthWorkspaceSlugRouteRoute;
    };
    "/_auth/$workspaceSlug/access-denied": {
      id: "/_auth/$workspaceSlug/access-denied";
      path: "/access-denied";
      fullPath: "/$workspaceSlug/access-denied";
      preLoaderRoute: typeof AuthWorkspaceSlugAccessDeniedRouteImport;
      parentRoute: typeof AuthWorkspaceSlugRouteRoute;
    };
    "/_auth/$workspaceSlug/settings": {
      id: "/_auth/$workspaceSlug/settings";
      path: "/settings";
      fullPath: "/$workspaceSlug/settings";
      preLoaderRoute: typeof AuthWorkspaceSlugSettingsRouteRouteImport;
      parentRoute: typeof AuthWorkspaceSlugRouteRoute;
    };
    "/_auth/$workspaceSlug/ontology-designer": {
      id: "/_auth/$workspaceSlug/ontology-designer";
      path: "/ontology-designer";
      fullPath: "/$workspaceSlug/ontology-designer";
      preLoaderRoute: typeof AuthWorkspaceSlugOntologyDesignerRouteRouteImport;
      parentRoute: typeof AuthWorkspaceSlugRouteRoute;
    };
    "/_auth/$workspaceSlug/data-manager": {
      id: "/_auth/$workspaceSlug/data-manager";
      path: "/data-manager";
      fullPath: "/$workspaceSlug/data-manager";
      preLoaderRoute: typeof AuthWorkspaceSlugDataManagerRouteRouteImport;
      parentRoute: typeof AuthWorkspaceSlugRouteRoute;
    };
    "/_auth/$workspaceSlug/dashboards": {
      id: "/_auth/$workspaceSlug/dashboards";
      path: "/dashboards";
      fullPath: "/$workspaceSlug/dashboards";
      preLoaderRoute: typeof AuthWorkspaceSlugDashboardsRouteRouteImport;
      parentRoute: typeof AuthWorkspaceSlugRouteRoute;
    };
    "/_auth/$workspaceSlug/settings/": {
      id: "/_auth/$workspaceSlug/settings/";
      path: "/";
      fullPath: "/$workspaceSlug/settings/";
      preLoaderRoute: typeof AuthWorkspaceSlugSettingsIndexRouteImport;
      parentRoute: typeof AuthWorkspaceSlugSettingsRouteRoute;
    };
    "/_auth/$workspaceSlug/ontology-designer/": {
      id: "/_auth/$workspaceSlug/ontology-designer/";
      path: "/";
      fullPath: "/$workspaceSlug/ontology-designer/";
      preLoaderRoute: typeof AuthWorkspaceSlugOntologyDesignerIndexRouteImport;
      parentRoute: typeof AuthWorkspaceSlugOntologyDesignerRouteRoute;
    };
    "/_auth/$workspaceSlug/individual-manager/": {
      id: "/_auth/$workspaceSlug/individual-manager/";
      path: "/individual-manager";
      fullPath: "/$workspaceSlug/individual-manager/";
      preLoaderRoute: typeof AuthWorkspaceSlugIndividualManagerIndexRouteImport;
      parentRoute: typeof AuthWorkspaceSlugRouteRoute;
    };
    "/_auth/$workspaceSlug/data-manager/": {
      id: "/_auth/$workspaceSlug/data-manager/";
      path: "/";
      fullPath: "/$workspaceSlug/data-manager/";
      preLoaderRoute: typeof AuthWorkspaceSlugDataManagerIndexRouteImport;
      parentRoute: typeof AuthWorkspaceSlugDataManagerRouteRoute;
    };
    "/_auth/$workspaceSlug/dashboards/": {
      id: "/_auth/$workspaceSlug/dashboards/";
      path: "/";
      fullPath: "/$workspaceSlug/dashboards/";
      preLoaderRoute: typeof AuthWorkspaceSlugDashboardsIndexRouteImport;
      parentRoute: typeof AuthWorkspaceSlugDashboardsRouteRoute;
    };
    "/public/dashboards/$workspaceSlug/$dashboardId": {
      id: "/public/dashboards/$workspaceSlug/$dashboardId";
      path: "/public/dashboards/$workspaceSlug/$dashboardId";
      fullPath: "/public/dashboards/$workspaceSlug/$dashboardId";
      preLoaderRoute: typeof PublicDashboardsWorkspaceSlugDashboardIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/(no-workspace)/invites/$inviteId": {
      id: "/_auth/(no-workspace)/invites/$inviteId";
      path: "/invites/$inviteId";
      fullPath: "/invites/$inviteId";
      preLoaderRoute: typeof AuthnoWorkspaceInvitesInviteIdRouteImport;
      parentRoute: typeof AuthnoWorkspaceRouteRoute;
    };
    "/_auth/$workspaceSlug/settings/$tabName": {
      id: "/_auth/$workspaceSlug/settings/$tabName";
      path: "/$tabName";
      fullPath: "/$workspaceSlug/settings/$tabName";
      preLoaderRoute: typeof AuthWorkspaceSlugSettingsTabNameRouteImport;
      parentRoute: typeof AuthWorkspaceSlugSettingsRouteRoute;
    };
    "/_auth/$workspaceSlug/ontology-designer/concept-creator": {
      id: "/_auth/$workspaceSlug/ontology-designer/concept-creator";
      path: "/concept-creator";
      fullPath: "/$workspaceSlug/ontology-designer/concept-creator";
      preLoaderRoute: typeof AuthWorkspaceSlugOntologyDesignerConceptCreatorRouteImport;
      parentRoute: typeof AuthWorkspaceSlugOntologyDesignerRouteRoute;
    };
    "/_auth/$workspaceSlug/ontology-designer/$conceptId": {
      id: "/_auth/$workspaceSlug/ontology-designer/$conceptId";
      path: "/$conceptId";
      fullPath: "/$workspaceSlug/ontology-designer/$conceptId";
      preLoaderRoute: typeof AuthWorkspaceSlugOntologyDesignerConceptIdRouteImport;
      parentRoute: typeof AuthWorkspaceSlugOntologyDesignerRouteRoute;
    };
    "/_auth/$workspaceSlug/data-manager/data-import": {
      id: "/_auth/$workspaceSlug/data-manager/data-import";
      path: "/data-import";
      fullPath: "/$workspaceSlug/data-manager/data-import";
      preLoaderRoute: typeof AuthWorkspaceSlugDataManagerDataImportRouteImport;
      parentRoute: typeof AuthWorkspaceSlugDataManagerRouteRoute;
    };
    "/_auth/$workspaceSlug/data-manager/$datasetId": {
      id: "/_auth/$workspaceSlug/data-manager/$datasetId";
      path: "/$datasetId";
      fullPath: "/$workspaceSlug/data-manager/$datasetId";
      preLoaderRoute: typeof AuthWorkspaceSlugDataManagerDatasetIdRouteImport;
      parentRoute: typeof AuthWorkspaceSlugDataManagerRouteRoute;
    };
    "/_auth/$workspaceSlug/d/$slugOrId": {
      id: "/_auth/$workspaceSlug/d/$slugOrId";
      path: "/d/$slugOrId";
      fullPath: "/$workspaceSlug/d/$slugOrId";
      preLoaderRoute: typeof AuthWorkspaceSlugDSlugOrIdRouteImport;
      parentRoute: typeof AuthWorkspaceSlugRouteRoute;
    };
    "/_auth/$workspaceSlug/individual-manager/$conceptId": {
      id: "/_auth/$workspaceSlug/individual-manager/$conceptId";
      path: "/individual-manager/$conceptId";
      fullPath: "/$workspaceSlug/individual-manager/$conceptId";
      preLoaderRoute: typeof AuthWorkspaceSlugIndividualManagerConceptIdRouteRouteImport;
      parentRoute: typeof AuthWorkspaceSlugRouteRoute;
    };
    "/_auth/$workspaceSlug/individual-manager/$conceptId/": {
      id: "/_auth/$workspaceSlug/individual-manager/$conceptId/";
      path: "/";
      fullPath: "/$workspaceSlug/individual-manager/$conceptId/";
      preLoaderRoute: typeof AuthWorkspaceSlugIndividualManagerConceptIdIndexRouteImport;
      parentRoute: typeof AuthWorkspaceSlugIndividualManagerConceptIdRouteRoute;
    };
    "/_auth/$workspaceSlug/individual-manager/$conceptId/$individualId": {
      id: "/_auth/$workspaceSlug/individual-manager/$conceptId/$individualId";
      path: "/$individualId";
      fullPath: "/$workspaceSlug/individual-manager/$conceptId/$individualId";
      preLoaderRoute: typeof AuthWorkspaceSlugIndividualManagerConceptIdIndividualIdRouteImport;
      parentRoute: typeof AuthWorkspaceSlugIndividualManagerConceptIdRouteRoute;
    };
    "/_auth/$workspaceSlug/dashboards/preview/$dashboardId": {
      id: "/_auth/$workspaceSlug/dashboards/preview/$dashboardId";
      path: "/preview/$dashboardId";
      fullPath: "/$workspaceSlug/dashboards/preview/$dashboardId";
      preLoaderRoute: typeof AuthWorkspaceSlugDashboardsPreviewDashboardIdRouteImport;
      parentRoute: typeof AuthWorkspaceSlugDashboardsRouteRoute;
    };
    "/_auth/$workspaceSlug/dashboards/edit/$dashboardId": {
      id: "/_auth/$workspaceSlug/dashboards/edit/$dashboardId";
      path: "/edit/$dashboardId";
      fullPath: "/$workspaceSlug/dashboards/edit/$dashboardId";
      preLoaderRoute: typeof AuthWorkspaceSlugDashboardsEditDashboardIdRouteImport;
      parentRoute: typeof AuthWorkspaceSlugDashboardsRouteRoute;
    };
  }
}

interface AuthWorkspaceSlugDashboardsRouteRouteChildren {
  AuthWorkspaceSlugDashboardsIndexRoute: typeof AuthWorkspaceSlugDashboardsIndexRoute;
  AuthWorkspaceSlugDashboardsEditDashboardIdRoute: typeof AuthWorkspaceSlugDashboardsEditDashboardIdRoute;
  AuthWorkspaceSlugDashboardsPreviewDashboardIdRoute: typeof AuthWorkspaceSlugDashboardsPreviewDashboardIdRoute;
}

const AuthWorkspaceSlugDashboardsRouteRouteChildren: AuthWorkspaceSlugDashboardsRouteRouteChildren =
  {
    AuthWorkspaceSlugDashboardsIndexRoute:
      AuthWorkspaceSlugDashboardsIndexRoute,
    AuthWorkspaceSlugDashboardsEditDashboardIdRoute:
      AuthWorkspaceSlugDashboardsEditDashboardIdRoute,
    AuthWorkspaceSlugDashboardsPreviewDashboardIdRoute:
      AuthWorkspaceSlugDashboardsPreviewDashboardIdRoute,
  };

const AuthWorkspaceSlugDashboardsRouteRouteWithChildren =
  AuthWorkspaceSlugDashboardsRouteRoute._addFileChildren(
    AuthWorkspaceSlugDashboardsRouteRouteChildren,
  );

interface AuthWorkspaceSlugDataManagerRouteRouteChildren {
  AuthWorkspaceSlugDataManagerDatasetIdRoute: typeof AuthWorkspaceSlugDataManagerDatasetIdRoute;
  AuthWorkspaceSlugDataManagerDataImportRoute: typeof AuthWorkspaceSlugDataManagerDataImportRoute;
  AuthWorkspaceSlugDataManagerIndexRoute: typeof AuthWorkspaceSlugDataManagerIndexRoute;
}

const AuthWorkspaceSlugDataManagerRouteRouteChildren: AuthWorkspaceSlugDataManagerRouteRouteChildren =
  {
    AuthWorkspaceSlugDataManagerDatasetIdRoute:
      AuthWorkspaceSlugDataManagerDatasetIdRoute,
    AuthWorkspaceSlugDataManagerDataImportRoute:
      AuthWorkspaceSlugDataManagerDataImportRoute,
    AuthWorkspaceSlugDataManagerIndexRoute:
      AuthWorkspaceSlugDataManagerIndexRoute,
  };

const AuthWorkspaceSlugDataManagerRouteRouteWithChildren =
  AuthWorkspaceSlugDataManagerRouteRoute._addFileChildren(
    AuthWorkspaceSlugDataManagerRouteRouteChildren,
  );

interface AuthWorkspaceSlugOntologyDesignerRouteRouteChildren {
  AuthWorkspaceSlugOntologyDesignerConceptIdRoute: typeof AuthWorkspaceSlugOntologyDesignerConceptIdRoute;
  AuthWorkspaceSlugOntologyDesignerConceptCreatorRoute: typeof AuthWorkspaceSlugOntologyDesignerConceptCreatorRoute;
  AuthWorkspaceSlugOntologyDesignerIndexRoute: typeof AuthWorkspaceSlugOntologyDesignerIndexRoute;
}

const AuthWorkspaceSlugOntologyDesignerRouteRouteChildren: AuthWorkspaceSlugOntologyDesignerRouteRouteChildren =
  {
    AuthWorkspaceSlugOntologyDesignerConceptIdRoute:
      AuthWorkspaceSlugOntologyDesignerConceptIdRoute,
    AuthWorkspaceSlugOntologyDesignerConceptCreatorRoute:
      AuthWorkspaceSlugOntologyDesignerConceptCreatorRoute,
    AuthWorkspaceSlugOntologyDesignerIndexRoute:
      AuthWorkspaceSlugOntologyDesignerIndexRoute,
  };

const AuthWorkspaceSlugOntologyDesignerRouteRouteWithChildren =
  AuthWorkspaceSlugOntologyDesignerRouteRoute._addFileChildren(
    AuthWorkspaceSlugOntologyDesignerRouteRouteChildren,
  );

interface AuthWorkspaceSlugSettingsRouteRouteChildren {
  AuthWorkspaceSlugSettingsTabNameRoute: typeof AuthWorkspaceSlugSettingsTabNameRoute;
  AuthWorkspaceSlugSettingsIndexRoute: typeof AuthWorkspaceSlugSettingsIndexRoute;
}

const AuthWorkspaceSlugSettingsRouteRouteChildren: AuthWorkspaceSlugSettingsRouteRouteChildren =
  {
    AuthWorkspaceSlugSettingsTabNameRoute:
      AuthWorkspaceSlugSettingsTabNameRoute,
    AuthWorkspaceSlugSettingsIndexRoute: AuthWorkspaceSlugSettingsIndexRoute,
  };

const AuthWorkspaceSlugSettingsRouteRouteWithChildren =
  AuthWorkspaceSlugSettingsRouteRoute._addFileChildren(
    AuthWorkspaceSlugSettingsRouteRouteChildren,
  );

interface AuthWorkspaceSlugIndividualManagerConceptIdRouteRouteChildren {
  AuthWorkspaceSlugIndividualManagerConceptIdIndividualIdRoute: typeof AuthWorkspaceSlugIndividualManagerConceptIdIndividualIdRoute;
  AuthWorkspaceSlugIndividualManagerConceptIdIndexRoute: typeof AuthWorkspaceSlugIndividualManagerConceptIdIndexRoute;
}

const AuthWorkspaceSlugIndividualManagerConceptIdRouteRouteChildren: AuthWorkspaceSlugIndividualManagerConceptIdRouteRouteChildren =
  {
    AuthWorkspaceSlugIndividualManagerConceptIdIndividualIdRoute:
      AuthWorkspaceSlugIndividualManagerConceptIdIndividualIdRoute,
    AuthWorkspaceSlugIndividualManagerConceptIdIndexRoute:
      AuthWorkspaceSlugIndividualManagerConceptIdIndexRoute,
  };

const AuthWorkspaceSlugIndividualManagerConceptIdRouteRouteWithChildren =
  AuthWorkspaceSlugIndividualManagerConceptIdRouteRoute._addFileChildren(
    AuthWorkspaceSlugIndividualManagerConceptIdRouteRouteChildren,
  );

interface AuthWorkspaceSlugRouteRouteChildren {
  AuthWorkspaceSlugDashboardsRouteRoute: typeof AuthWorkspaceSlugDashboardsRouteRouteWithChildren;
  AuthWorkspaceSlugDataManagerRouteRoute: typeof AuthWorkspaceSlugDataManagerRouteRouteWithChildren;
  AuthWorkspaceSlugOntologyDesignerRouteRoute: typeof AuthWorkspaceSlugOntologyDesignerRouteRouteWithChildren;
  AuthWorkspaceSlugSettingsRouteRoute: typeof AuthWorkspaceSlugSettingsRouteRouteWithChildren;
  AuthWorkspaceSlugAccessDeniedRoute: typeof AuthWorkspaceSlugAccessDeniedRoute;
  AuthWorkspaceSlugCheckoutRoute: typeof AuthWorkspaceSlugCheckoutRoute;
  AuthWorkspaceSlugDataExplorerRoute: typeof AuthWorkspaceSlugDataExplorerRoute;
  AuthWorkspaceSlugMapRoute: typeof AuthWorkspaceSlugMapRoute;
  AuthWorkspaceSlugProfileRoute: typeof AuthWorkspaceSlugProfileRoute;
  AuthWorkspaceSlugIndexRoute: typeof AuthWorkspaceSlugIndexRoute;
  AuthWorkspaceSlugIndividualManagerConceptIdRouteRoute: typeof AuthWorkspaceSlugIndividualManagerConceptIdRouteRouteWithChildren;
  AuthWorkspaceSlugDSlugOrIdRoute: typeof AuthWorkspaceSlugDSlugOrIdRoute;
  AuthWorkspaceSlugIndividualManagerIndexRoute: typeof AuthWorkspaceSlugIndividualManagerIndexRoute;
}

const AuthWorkspaceSlugRouteRouteChildren: AuthWorkspaceSlugRouteRouteChildren =
  {
    AuthWorkspaceSlugDashboardsRouteRoute:
      AuthWorkspaceSlugDashboardsRouteRouteWithChildren,
    AuthWorkspaceSlugDataManagerRouteRoute:
      AuthWorkspaceSlugDataManagerRouteRouteWithChildren,
    AuthWorkspaceSlugOntologyDesignerRouteRoute:
      AuthWorkspaceSlugOntologyDesignerRouteRouteWithChildren,
    AuthWorkspaceSlugSettingsRouteRoute:
      AuthWorkspaceSlugSettingsRouteRouteWithChildren,
    AuthWorkspaceSlugAccessDeniedRoute: AuthWorkspaceSlugAccessDeniedRoute,
    AuthWorkspaceSlugCheckoutRoute: AuthWorkspaceSlugCheckoutRoute,
    AuthWorkspaceSlugDataExplorerRoute: AuthWorkspaceSlugDataExplorerRoute,
    AuthWorkspaceSlugMapRoute: AuthWorkspaceSlugMapRoute,
    AuthWorkspaceSlugProfileRoute: AuthWorkspaceSlugProfileRoute,
    AuthWorkspaceSlugIndexRoute: AuthWorkspaceSlugIndexRoute,
    AuthWorkspaceSlugIndividualManagerConceptIdRouteRoute:
      AuthWorkspaceSlugIndividualManagerConceptIdRouteRouteWithChildren,
    AuthWorkspaceSlugDSlugOrIdRoute: AuthWorkspaceSlugDSlugOrIdRoute,
    AuthWorkspaceSlugIndividualManagerIndexRoute:
      AuthWorkspaceSlugIndividualManagerIndexRoute,
  };

const AuthWorkspaceSlugRouteRouteWithChildren =
  AuthWorkspaceSlugRouteRoute._addFileChildren(
    AuthWorkspaceSlugRouteRouteChildren,
  );

interface AuthnoWorkspaceRouteRouteChildren {
  AuthnoWorkspaceInvalidWorkspaceRoute: typeof AuthnoWorkspaceInvalidWorkspaceRoute;
  AuthnoWorkspaceIndexRoute: typeof AuthnoWorkspaceIndexRoute;
  AuthnoWorkspaceInvitesInviteIdRoute: typeof AuthnoWorkspaceInvitesInviteIdRoute;
}

const AuthnoWorkspaceRouteRouteChildren: AuthnoWorkspaceRouteRouteChildren = {
  AuthnoWorkspaceInvalidWorkspaceRoute: AuthnoWorkspaceInvalidWorkspaceRoute,
  AuthnoWorkspaceIndexRoute: AuthnoWorkspaceIndexRoute,
  AuthnoWorkspaceInvitesInviteIdRoute: AuthnoWorkspaceInvitesInviteIdRoute,
};

const AuthnoWorkspaceRouteRouteWithChildren =
  AuthnoWorkspaceRouteRoute._addFileChildren(AuthnoWorkspaceRouteRouteChildren);

interface AuthRouteRouteChildren {
  AuthWorkspaceSlugRouteRoute: typeof AuthWorkspaceSlugRouteRouteWithChildren;
  AuthnoWorkspaceRouteRoute: typeof AuthnoWorkspaceRouteRouteWithChildren;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthWorkspaceSlugRouteRoute: AuthWorkspaceSlugRouteRouteWithChildren,
  AuthnoWorkspaceRouteRoute: AuthnoWorkspaceRouteRouteWithChildren,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  SigninRoute: SigninRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  DSlugOrIdRoute: DSlugOrIdRoute,
  PublicDashboardsWorkspaceSlugDashboardIdRoute:
    PublicDashboardsWorkspaceSlugDashboardIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
