-- Adding a value to an existing enum cannot be generated by `db diff`.
-- migra's strategy is to rename the old type, create a new one, repoint
-- columns, and drop the old type, which fails here because
-- `rpc_datasets__add_dataset` declares a parameter of this type and the
-- rename leaves that signature depending on the renamed type:
--   ERROR: cannot drop type datasets__source_type__old_version_to_be_dropped
--   because other objects depend on it (SQLSTATE 2BP01)
-- The repo already handles this by hand for the same enum; see
-- 20260504000010_add_xlsx_file_source_type_enum_value.sql.
--
-- This migration is deliberately limited to the label addition. Everything
-- else the PDF import needs (the three new enum types, the
-- `datasets__pdf_file` table, its policies, and the RPC) is generated by
-- `pnpm db:new-migration` from `supabase/schemas/`, which is also what
-- appends the privileges `db diff` cannot see.
--
-- The new label must be committed in its own migration before anything can
-- use it, otherwise Postgres rejects the reference (PG 55P04).
alter type public.datasets__source_type
add value if not exists 'pdf_file';
