-- Adding a value to an existing enum cannot be generated by `db diff`.
-- migra's strategy is to rename the old type, create a new one, repoint
-- columns, and drop the old type, which fails here because
-- `rpc_datasets__add_dataset` declares a parameter of this type and the
-- rename leaves that signature depending on the renamed type:
--   ERROR: cannot drop type datasets__source_type__old_version_to_be_dropped
--   because other objects depend on it (SQLSTATE 2BP01)
-- The repo already handles this by hand for the same enum; see
-- 20260504000010_add_xlsx_file_source_type_enum_value.sql.
--
-- New enum label must be committed before it can be used (PG 55P04).
alter type public.datasets__source_type
add value if not exists 'pdf_file';

-- How a PDF table's structure was determined. Hand-written alongside the
-- label above so the two arrive together; a generated migration for this
-- type alone would also carry unrelated pre-existing analytics drift.
create type public.datasets__pdf_detection_mode as enum(
  'tagged',
  'lattice',
  'stream',
  'manual'
);
