
-- Privileges that `supabase db diff` cannot see: default, schema, column,
-- and view grants. Appended by `pnpm db:new-migration` from what
-- `supabase/schemas/` declares. Do not hand-edit; re-run the command.
revoke all privileges on function public.concept_attributes__validate_label_and_identifiers() from public, anon, authenticated, service_role;
revoke all privileges on function public.dashboards__log_deleted_analytics_event() from public, anon, authenticated, service_role;
revoke all privileges on function public.dashboards__prevent_workspace_id_change() from public, anon, authenticated, service_role;
revoke all privileges on function public.datasets__log_deleted_analytics_event() from public, anon, authenticated, service_role;
revoke all privileges on function public.datasets__prevent_workspace_id_change() from public, anon, authenticated, service_role;
revoke all privileges on function public.maps__prevent_workspace_id_change() from public, anon, authenticated, service_role;
revoke all privileges on function public.resource_shares__validate_principal_workspace() from public, anon, authenticated, service_role;
revoke all privileges on function public.resource_shares__validate_resource_workspace() from public, anon, authenticated, service_role;
revoke all privileges on function public.rpc_datasets__add_csv_file_dataset(p_dataset_id uuid, p_workspace_id uuid, p_dataset_name text, p_dataset_description text, p_columns dataset_column_input[], p_is_in_cloud_storage boolean, p_size_in_bytes bigint, p_rows_to_skip integer, p_quote_char util__nullable_text, p_escape_char util__nullable_text, p_delimiter text, p_newline_delimiter text, p_comment_char util__nullable_text, p_has_header boolean, p_date_format datasets__csv_file__date_format) from public, anon, authenticated, service_role;
grant EXECUTE on function public.rpc_datasets__add_csv_file_dataset(p_dataset_id uuid, p_workspace_id uuid, p_dataset_name text, p_dataset_description text, p_columns dataset_column_input[], p_is_in_cloud_storage boolean, p_size_in_bytes bigint, p_rows_to_skip integer, p_quote_char util__nullable_text, p_escape_char util__nullable_text, p_delimiter text, p_newline_delimiter text, p_comment_char util__nullable_text, p_has_header boolean, p_date_format datasets__csv_file__date_format) to "authenticated";
revoke all privileges on function public.rpc_datasets__add_dataset(p_dataset_id uuid, p_workspace_id uuid, p_dataset_name text, p_dataset_description text, p_dataset_source_type datasets__source_type, p_columns dataset_column_input[]) from public, anon, authenticated, service_role;
grant EXECUTE on function public.rpc_datasets__add_dataset(p_dataset_id uuid, p_workspace_id uuid, p_dataset_name text, p_dataset_description text, p_dataset_source_type datasets__source_type, p_columns dataset_column_input[]) to "authenticated";
revoke all privileges on function public.rpc_datasets__add_google_sheets_dataset(p_dataset_id uuid, p_workspace_id uuid, p_dataset_name text, p_dataset_description text, p_columns dataset_column_input[], p_google_account_id text, p_google_document_id text, p_rows_to_skip integer, p_sheet_name util__nullable_text) from public, anon, authenticated, service_role;
grant EXECUTE on function public.rpc_datasets__add_google_sheets_dataset(p_dataset_id uuid, p_workspace_id uuid, p_dataset_name text, p_dataset_description text, p_columns dataset_column_input[], p_google_account_id text, p_google_document_id text, p_rows_to_skip integer, p_sheet_name util__nullable_text) to "authenticated";
revoke all privileges on function public.rpc_datasets__add_open_data_dataset(p_dataset_id uuid, p_workspace_id uuid, p_dataset_name text, p_dataset_description text, p_catalog_entry_id uuid, p_columns dataset_column_input[]) from public, anon, authenticated, service_role;
grant EXECUTE on function public.rpc_datasets__add_open_data_dataset(p_dataset_id uuid, p_workspace_id uuid, p_dataset_name text, p_dataset_description text, p_catalog_entry_id uuid, p_columns dataset_column_input[]) to "authenticated";
revoke all privileges on function public.rpc_datasets__add_virtual_dataset(p_dataset_id uuid, p_workspace_id uuid, p_dataset_name text, p_dataset_description text, p_columns dataset_column_input[], p_raw_sql text) from public, anon, authenticated, service_role;
grant EXECUTE on function public.rpc_datasets__add_virtual_dataset(p_dataset_id uuid, p_workspace_id uuid, p_dataset_name text, p_dataset_description text, p_columns dataset_column_input[], p_raw_sql text) to "authenticated";
revoke all privileges on function public.rpc_datasets__add_xlsx_file_dataset(p_dataset_id uuid, p_workspace_id uuid, p_dataset_name text, p_dataset_description text, p_columns dataset_column_input[], p_is_in_cloud_storage boolean, p_size_in_bytes bigint, p_rows_to_skip integer, p_sheet_name util__nullable_text, p_has_header boolean, p_date_format datasets__csv_file__date_format) from public, anon, authenticated, service_role;
grant EXECUTE on function public.rpc_datasets__add_xlsx_file_dataset(p_dataset_id uuid, p_workspace_id uuid, p_dataset_name text, p_dataset_description text, p_columns dataset_column_input[], p_is_in_cloud_storage boolean, p_size_in_bytes bigint, p_rows_to_skip integer, p_sheet_name util__nullable_text, p_has_header boolean, p_date_format datasets__csv_file__date_format) to "authenticated";
revoke all privileges on function public.rpc_workspaces__create_with_owner(p_workspace_name text, p_workspace_slug text, p_full_name text, p_display_name text) from public, anon, authenticated, service_role;
grant EXECUTE on function public.rpc_workspaces__create_with_owner(p_workspace_name text, p_workspace_slug text, p_full_name text, p_display_name text) to "authenticated";
revoke all privileges on function public.tr_workspaces__seed_builtin_role_groups() from public, anon, authenticated, service_role;
revoke all privileges on function public.usage_analytics_events__set_category() from public, anon, authenticated, service_role;
revoke all privileges on function public.user_group_memberships__cleanup_on_workspace_member_removed() from public, anon, authenticated, service_role;
revoke all privileges on function public.user_profiles__prevent_id_changes() from public, anon, authenticated, service_role;
revoke all privileges on function public.util__analytics_event_category(p_event_name text) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__analytics_event_category(p_event_name text) to "authenticated";
grant EXECUTE on function public.util__analytics_event_category(p_event_name text) to "service_role";
revoke all privileges on function public.util__auth_user_can_access_resource_in_workspace(p_resource_type resource_type, p_resource_id uuid, p_workspace_id uuid, p_required_role role_level) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__auth_user_can_access_resource_in_workspace(p_resource_type resource_type, p_resource_id uuid, p_workspace_id uuid, p_required_role role_level) to "authenticated";
revoke all privileges on function public.util__auth_user_can_access_resource(p_resource_type resource_type, p_resource_id uuid, p_min_role role_level) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__auth_user_can_access_resource(p_resource_type resource_type, p_resource_id uuid, p_min_role role_level) to "authenticated";
revoke all privileges on function public.util__auth_user_can_delete_resource(p_resource_type resource_type, p_resource_id uuid) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__auth_user_can_delete_resource(p_resource_type resource_type, p_resource_id uuid) to "authenticated";
revoke all privileges on function public.util__auth_user_can_insert_workspace_resource(p_workspace_id uuid, p_resource_type resource_type, p_owner_id uuid) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__auth_user_can_insert_workspace_resource(p_workspace_id uuid, p_resource_type resource_type, p_owner_id uuid) to "authenticated";
revoke all privileges on function public.util__auth_user_can_update_resource(p_resource_type resource_type, p_resource_id uuid) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__auth_user_can_update_resource(p_resource_type resource_type, p_resource_id uuid) to "authenticated";
revoke all privileges on function public.util__auth_user_may_select_dashboard(p_dashboard_id uuid) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__auth_user_may_select_dashboard(p_dashboard_id uuid) to "authenticated";
revoke all privileges on function public.util__auth_user_may_select_dataset(p_dataset_id uuid) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__auth_user_may_select_dataset(p_dataset_id uuid) to "authenticated";
revoke all privileges on function public.util__auth_user_meets_min_app_role(p_workspace_id uuid, p_app app_type, p_min_role role_level) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__auth_user_meets_min_app_role(p_workspace_id uuid, p_app app_type, p_min_role role_level) to "authenticated";
revoke all privileges on function public.util__can_manage_workspace_settings(p_workspace_id uuid) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__can_manage_workspace_settings(p_workspace_id uuid) to "authenticated";
revoke all privileges on function public.util__email_domain(p_email text) from public, anon, authenticated, service_role;
revoke all privileges on function public.util__get_auth_user_app_role(p_workspace_id uuid, p_app app_type) from public, anon, authenticated, service_role;
revoke all privileges on function public.util__get_auth_user_owned_workspaces() from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__get_auth_user_owned_workspaces() to "authenticated";
revoke all privileges on function public.util__get_auth_user_user_group_ids(p_workspace_id uuid) from public, anon, authenticated, service_role;
revoke all privileges on function public.util__get_auth_user_workspaces() from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__get_auth_user_workspaces() to "authenticated";
revoke all privileges on function public.util__is_settings_admin(p_workspace_id uuid) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__is_settings_admin(p_workspace_id uuid) to "authenticated";
revoke all privileges on function public.util__rank_to_role_level(p_rank integer) from public, anon, authenticated, service_role;
revoke all privileges on function public.util__resource_effective_role(p_resource_type resource_type, p_resource_id uuid) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__resource_effective_role(p_resource_type resource_type, p_resource_id uuid) to "authenticated";
revoke all privileges on function public.util__resource_type_to_app_type(p_resource_type resource_type) from public, anon, authenticated, service_role;
revoke all privileges on function public.util__role_level_rank(p_role role_level) from public, anon, authenticated, service_role;
revoke all privileges on function public.util__set_updated_at() from public, anon, authenticated, service_role;
revoke all privileges on function public.util__storage_object_dashboard_id(p_object_name text) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__storage_object_dashboard_id(p_object_name text) to "anon";
grant EXECUTE on function public.util__storage_object_dashboard_id(p_object_name text) to "authenticated";
revoke all privileges on function public.util__storage_object_dataset_id(p_object_name text) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__storage_object_dataset_id(p_object_name text) to "authenticated";
revoke all privileges on function public.util__storage_object_snapshot_revision(p_object_name text) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__storage_object_snapshot_revision(p_object_name text) to "anon";
grant EXECUTE on function public.util__storage_object_snapshot_revision(p_object_name text) to "authenticated";
revoke all privileges on function public.util__storage_object_workspace_id(p_object_name text) from public, anon, authenticated, service_role;
grant EXECUTE on function public.util__storage_object_workspace_id(p_object_name text) to "authenticated";
revoke all privileges on function public.util__subscription_plan_rank(p_plan subscriptions__feature_plan_type) from public, anon, authenticated, service_role;
